location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    ingress:
      external: false
      targetPort: {{ targetPortOrDefault 8080 }}
      transport: http
      allowInsecure: true
    registries:
    - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
      identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: applicationinsights-connection-string
        value: '{{ .Env.ASPIREDEMOAPPLICATIONINSIGHTS_APPINSIGHTSCONNECTIONSTRING }}'
      - name: connectionstrings--aspiredemodb
        value: Server=tcp:{{ .Env.ASPIREDEMOSQLSERVER_SQLSERVERFQDN }},1433;Encrypt=True;Authentication="Active Directory Default";Database=aspiredemodb
      - name: connectionstrings--cache
        keyVaultUrl: '{{ .Env.SERVICE_BINDING_CACHEKV_ENDPOINT }}secrets/connectionString'
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
  template:
    containers:
    - image: {{ .Image }}
      name: aspiredemoapp
      env:
      - name: AZURE_CLIENT_ID
        value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
      - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
        value: "true"
      - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
        value: "true"
      - name: APPLICATIONINSIGHTS_CONNECTION_STRING
        secretRef: applicationinsights-connection-string
      - name: ConnectionStrings__aspiredemodb
        secretRef: connectionstrings--aspiredemodb
      - name: ConnectionStrings__cache
        secretRef: connectionstrings--cache
    scale:
      minReplicas: 1
tags:
  azd-service-name: aspiredemoapp
  aspire-resource-name: aspiredemoapp
